package greentic:component@0.6.1;

use greentic:provider-schema-core/schema-core-api@1.0.0;

world component-v0-v6-v0 {
  export descriptor;
  export runtime;
  export qa;
  export component-i18n;
  export schema-core-api;
}
